table 'gold jobs_per_contract_type'
	lineageTag: 795d1d18-ec95-48f2-a815-998d1404be86

	column contract_type_std
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: efb74fc7-3331-4dff-bec3-219d639fc7b3
		summarizeBy: none
		sourceColumn: contract_type_std

		annotation SummarizationSetBy = Automatic

	column job_count
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2283f80c-9ace-4549-b40f-931cc2bff190
		summarizeBy: sum
		sourceColumn: job_count

		annotation SummarizationSetBy = Automatic

	partition 'gold jobs_per_contract_type' = m
		mode: directQuery
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "airflow"),
				    gold_jobs_per_contract_type = Source{[Schema="gold",Item="jobs_per_contract_type"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(gold_jobs_per_contract_type,{{"contract_type_std", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

